 dbhost: cockroachdb-fuga.cockroach-db-fuga.svc.cluster.local


 ingress:
  annotations:
   nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Cluster-Name: Fuga";
  hosts:
    - host: solidus.domains.leaf.cloud
      paths:
        - path: /
          pathType: Prefix
    - host: multi-cluster-demo.com
      paths:
        - path: /
          pathType: Prefix
    - paths:
        - path: /
          pathType: Prefix